### PR TITLE
CDM-78:  Create Mentors page

### PR DESCRIPTION
**Pull request by catarinapm**
### Reviewers
- [x] @mariasbl 
- [x] @danielaprado

### CODE REVIEW

**Comment by catarinapm** [comment]
Needs to be merged after About Us page

**Review by danielaprado — CHANGES_REQUESTED** [review]
Could you fix the build error? So we can check the preview link before approving 🙌 
image

**Comment by catarinapm** [comment]
> Needs to be merged after About Us page

Needs to be merged after About Us page to be ready for merge!

**Review by mariasbl — APPROVED** [review]

**Review by mariasbl — CHANGES_REQUESTED** [review]
- O gap entre os mentores devia ser mais pequeno, não -24

**Review by danielaprado — APPROVED** [review]

**Review by mariasbl — APPROVED** [review]

**Pull request merged**
