### PR TITLE
CDM-80: Update pages to singletons

### PR DESCRIPTION
**Pull request by catarinapm**
source: https://www.sanity.io/guides/singleton-document

### CODE REVIEW

**Review by danielaprado — CHANGES_REQUESTED** [review]
Can you update the pages schema so it has a title to prevent this from happening?
Screenshot 2024-02-13 at 15 17 19

**Review by danielaprado — COMMENTED** [review]
And it was a really good idea to add the singletons! U -> (! 🤏)🧠

**Review by danielaprado — APPROVED** [review]
I think we could avoid having so much lines by creating an array of objects, since they all have the same properties but as is is also fine by me

**Comment by catarinapm** [comment]
> And it was a really good idea to add the singletons! U -> (! 🤏)🧠

Thank you!

**Comment by catarinapm** [comment]
> I think we could avoid having so much lines by creating an array of objects, since they all have the same properties but as is is also fine by me

Yes it´s a good idea. Maybe we can do this in another branch

**Review by mariasbl — APPROVED** [review]

**Pull request merged**
